// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvox5LKbfVhMvRaCUGiLPB29iEL_cR3-Y',
    appId: '1:109587486706:web:61fe2dd746a931ac677d6b',
    messagingSenderId: '109587486706',
    projectId: 'gymsgg-mov',
    authDomain: 'gymsgg-mov.firebaseapp.com',
    storageBucket: 'gymsgg-mov.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBEnp8cYNp3T6jYvaL7aYG0b2JYlDnTg',
    appId: '1:109587486706:android:6e21bf7f4aef13fd677d6b',
    messagingSenderId: '109587486706',
    projectId: 'gymsgg-mov',
    storageBucket: 'gymsgg-mov.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpRN3ziwPN5cA8DryJLus3ibyYZ5n1Aw',
    appId: '1:109587486706:ios:4b8cf3705a86723c677d6b',
    messagingSenderId: '109587486706',
    projectId: 'gymsgg-mov',
    storageBucket: 'gymsgg-mov.firebasestorage.app',
    iosBundleId: 'com.example.gymsggApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpRN3ziwPN5cA8DryJLus3ibyYZ5n1Aw',
    appId: '1:109587486706:ios:4b8cf3705a86723c677d6b',
    messagingSenderId: '109587486706',
    projectId: 'gymsgg-mov',
    storageBucket: 'gymsgg-mov.firebasestorage.app',
    iosBundleId: 'com.example.gymsggApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvox5LKbfVhMvRaCUGiLPB29iEL_cR3-Y',
    appId: '1:109587486706:web:5afd58ed1f260f7a677d6b',
    messagingSenderId: '109587486706',
    projectId: 'gymsgg-mov',
    authDomain: 'gymsgg-mov.firebaseapp.com',
    storageBucket: 'gymsgg-mov.firebasestorage.app',
  );
}
